### ISSUE TITLE
cmd vs entrypoint: one or the other

### ISSUE THREAD

**Issue by langdon** [BU-Spark/se-bch-als-msg-banking#22]
unless you have a really good reason to, you should only have one of `CMD` & `ENTRYPOINT`. If you have a good reason, it should have a comment.
https://github.com/BU-Spark/se-bch-als-msg-banking/blob/b2b342ae09607386d3d8b7dbb4346092239238a0/backend/Dockerfile#L8

**Comment by diegosbu** [comment]
Docker container does not run without both entrypoint and cmd lines.
