### ISSUE TITLE
 Request for Spark! Tech Resources for se-bch-als-msg-banking; encrypted secrets/artifact write access

### ISSUE THREAD

**Issue by diegosbu** [BU-Spark/se-bch-als-msg-banking#39]
I (Diego Sanchez, diegos@bu.edu) need to add encrypted secrets to this repository to allow our github actions to continuously deploy the backend. We use Google Artifact Registry, which hosts our backend docker image, and need to add the service account key to the encrypted secrets to allow github actions to access it securely. I need admin access to the repo to add this encrypted secret. We also need the existing github-action service account in GCP to be given write access permissions to the artifact registry. This is so it can build and push the docker image. The project is due end of May 4th, but this would ideally be set up by end of this upcoming week.

Thank you!

**Comment by IanSaucy** [comment]
I've added you as an admin on the repo. Let me know if you need anything else. Otherwise, please close the issue!
