### ISSUE TITLE
Request for Spark! Tech Resources for se-bch-als-msg-banking; service account artifact write access

### ISSUE THREAD

**Issue by diegosbu** [BU-Spark/se-bch-als-msg-banking#42]
We need the existing github-action service account (github-action-398067076@als-message-banking.iam.gserviceaccount.com) in the google cloud platform to be given write access permission to the project's artifact registry. It is currently unable to push the docker image to the artifact registry repo, where our backend docker image lives. Giving it this permission will allow our workflow file to continuously deploy changes made to the backend. The project is due end of May 4th.

Thank you!

**Comment by IanSaucy** [comment]
@diegosbu I'm not exactly sure what your request is here. Do you have a special service account that needs permission to access this repo?

**Comment by diegosbu** [comment]
@IanSaucy  Our backend is hosted on the google artifact registry using a docker image repo placed there. In order for our workflow file to be able to push to this repo, the corresponding service account (github-action-398067076@als-message-banking.iam.gserviceaccount.com) in the google cloud must be given a role which allows it to push. The service account currently only has these roles: API Keys Viewer, Cloud Run Viewer, Firebase Authentication Admin, Firebase Hosting Admin. These currently allows it to deploy the frontend, but we now also need it to be given the "Artifact Registry Writer" role/permission so it can deploy the backend.

**Comment by IanSaucy** [comment]
I updated the permission. But for future reference it's a permission that's set on Google Cloud Console and you have the permissions/ability to set it yourself!

Ian
